homepage: "https://github.com/mvel/mvel/"
language: jvm
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/mvel/mvel/"
sanitizers:
  - address
vendor_ccs:
  - "bug-disclosure@code-intelligence.com"