homepage: "http://php.net/"
language: c++
primary_contact: "stas@php.net"
auto_ccs:
 - "smalyshev@gmail.com"
 - "nikita.ppv@gmail.com"
 - "dmitrystogov@gmail.com"
 - "ilija.tovilo@me.com"
fuzzing_engines:
  - "afl"
  - "honggfuzz"
  - "libfuzzer"
sanitizers:
 - address
 - undefined
 - memory
architectures:
 - x86_64
 - i386
view_restrictions: none
main_repo: 'https://github.com/php/php-src.git'
