homepage: "https://www.documentliberation.org"
language: c++
primary_contact: "dtardon@redhat.com"
sanitizers:
  - address
# Disabled MSAN because of https://github.com/threatcode/oss-fuzz/issues/6294
# - memory
  - undefined
