homepage: "https://github.com/jboss-logging/jboss-logging"
language: jvm
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/jboss-logging/jboss-logging"
sanitizers:
  - address
vendor_ccs:
  - "bug-disclosure@code-intelligence.com"
  - "hlin@code-intelligence.com"