homepage: "https://www.jbig2dec.com"
language: c++
primary_contact: sebastian.rasmussen@artifex.com
fuzzing_engines:
 - afl
 - honggfuzz
 - libfuzzer
 - centipede
sanitizers:
  - address
  - memory
main_repo: 'git://git.ghostscript.com/jbig2dec.git'
