homepage: https://github.com/uqfoundation/dill
main_repo: https://github.com/uqfoundation/dill
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
