homepage: "https://github.com/WizardMac/ReadStat"
language: c++
primary_contact: "emmiller@gmail.com"
main_repo: 'https://github.com/WizardMac/ReadStat'
fuzzing_engines:
 - afl
 - honggfuzz
 - libfuzzer
 - centipede
