homepage: "https://tukaani.org/xz/"
language: c++
primary_contact: "jiat0218@gmail.com"
auto_ccs:
  - "lasse.collin@tukaani.org"
  - "bshas3@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://github.com/tukaani-project/xz.git'
