homepage: https://github.com/python-hyper/rfc3986
main_repo: https://github.com/python-hyper/rfc3986
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
