fuzzing_engines:
- libfuzzer
homepage: https://github.com/davidhalter/parso
language: python
main_repo: https://github.com/davidhalter/parso
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
