homepage: https://github.com/betodealmeida/python-rison
main_repo: https://github.com/betodealmeida/python-rison
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
