homepage: "https://github.com/ostreedev/ostree"
main_repo: 'https://github.com/ostreedev/ostree'
language: c
primary_contact: "walters@verbum.org"
auto_ccs:
  - "dbn@endlessos.org"
  - "david@adalogics.com"
fuzzing_engines:
 - afl
 - honggfuzz
 - libfuzzer
 - centipede
