homepage: "https://www.mpg123.de"
language: c++
primary_contact: "maintainer@mpg123.org"

sanitizers:
  - address
  - undefined
  - memory

labels:
  read_fuzzer:
    - sundew
  decode_fuzzer:
    - sundew
fuzzing_engines:
 - afl
 - honggfuzz
 - libfuzzer
 - centipede
